baseURL = 'https://pngdeity.ru/blog/'
languageCode = 'en-us'
title = 'pngdeity'
theme = 'ananke'

enableGitInfo = true
ignoreLogs = ['warning-goldmark-raw-html']

[taxonomies]
tag = 'tags'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
custom_css = ['theme.css']

[params.ananke.social.share]
icons = false
sharetext = true
networks = ['reddit', 'x-twitter']
