baseURL = 'https://pngdeity.ru/blog/'
locale = 'en-us'
title = 'pngdeity'

enableGitInfo = true
ignoreLogs = ['warning-goldmark-raw-html']

[taxonomies]
tag = 'tags'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
show_recent_posts = true

[params.ananke.social.share]
icons = false
sharetext = true
networks = ['reddit', 'x-twitter']

[params.ananke.social.networks.reddit]
slug = 'reddit'
label = 'Reddit'
link = 'https://reddit.com/submit/'
[params.ananke.social.networks.reddit.particles]
url = 'permalink'
title = 'title'
params = 'resubmit=true'

[params.ananke.social.networks.x-twitter]
slug = 'x-twitter'
label = 'X'
link = 'https://twitter.com/intent/tweet/'
[params.ananke.social.networks.x-twitter.particles]
text = 'description'
url = 'permalink'
